In [2]:
import pickle
import numpy as np

In [3]:
ohe_gender = pickle.load(open('models/sex_ohe.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/embarked_ohe.pkl','rb'))
classifier = pickle.load(open('models/classifier.pkl','rb'))

In [5]:
test_input = np.array([1, 'female', 30.0, 1, 0, 17.6, 'C'], dtype=object).reshape(1,7)

In [6]:
test_input

array([[1, 'female', 30.0, 1, 0, 17.6, 'C']], dtype=object)

In [8]:
test_input_gender = ohe_gender.transform(test_input[:,1].reshape(1,1))

/home/varsha/PracticePython/pracvenv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [9]:
test_input_gender

array([[1., 0.]])

In [25]:
test_input_gender

array([[1., 0.]])

In [11]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [12]:
test_input_age = test_input[:,2].reshape(1,1)

In [13]:
test_input_transformed = np.concatenate((test_input[:, [0,3,4,5]],test_input_age,test_input_gender , test_input_embarked), axis =1)

In [29]:
classifier.predict(test_input_transformed)

array([1])